### ISSUE TITLE
MileStone-Trask Release

### ISSUE THREAD

**Issue by kalyankondapally** [01org/ozone-wayland#402]
TODO:
1)Release notes.
2)Source release and test every thing works properly with appropriate Chromium release.

**Comment by kalyankondapally** [comment]
@rakuco @joone Issue to track next Release.

**Comment by rakuco** [comment]
@kalyankondapally what do you think of branching from 00db18396b496303ee36b887e8ac69060dec9b76? I've just tried Crosswalk with 45.0.2454.37 and it all built fine after reverting 16b723b55691aabaf2e8bf8897596bc5bcf9e0bc (since the Chromium commit is not in M45). I haven't tested a full Chromium build though. Maybe @joone can help with that?

**Comment by kalyankondapally** [comment]
@rakuco That should be ok. I can try the chromium build as @joone is on holiday. Do you want to push the new release branch ?

**Comment by rakuco** [comment]
I've just pushed a new branch called `Milestone-Trask`. It is basically master with 16b723b reverted. Next week, I'll do the regular adjustments (removing `.DEPS.git`, adding release notes etc).

**Comment by kalyankondapally** [comment]
@hobbitalastair  new release  branch has been pushed.

**Comment by hobbitalastair** [comment]
I've launched a build of Milestone-Trask against 45.0.2454.37.

Patch 0015 failed to apply for me, although it doesn't appear to be fixed upstream, so possibly a build issue on my side.

**Comment by hobbitalastair** [comment]
Hmm. The branch doesn't appear to be building against 45.0.2454.37... it fails while building boringssl.

**Comment by rakuco** [comment]
> Patch 0015 failed to apply for me, although it doesn't appear to be fixed upstream, so possibly a build issue on my side.

I've removed it from Milestone-Trask -- the upstream CL it is changing is not part of M45.

> Hmm. The branch doesn't appear to be building against 45.0.2454.37... it fails while building boringssl.

I've just tried it here and everything worked fine. My `GYP_DEFINES`: `disable_nacl=1 component=shared_library use_aura=1 chromeos=0 use_ozone=1 use_xkbcommon=1`.

**Comment by rakuco** [comment]
Actually, `component=shared_library` is causing some problems to link the final `chrome` binary, but I don't think they're related to the BoringSSL issue you've mentioned.

**Comment by hobbitalastair** [comment]
It appears that I needed to add _GNU_SOURCE to the CFLAGS for boringssl to build. It's a bit of a hack...

I'm suspicious that it's caused by some combination of gcc-5.2 and glibc 2.22, since the failure was this:

    [987/18593] CC obj/third_party/boringssl/src/crypto/bio/boringssl.socket_helper.o
    FAILED: cc -MMD -MF obj/third_party/boringssl/src/crypto/bio/boringssl.socket_helper.o.d -DV8_DEPRECATION_WARNINGS -D_FILE_OFFSET_BITS=64 -DCHROMIUM_BUILD -DCR_CLANG_REVISION=241602-2 -DUI_COMPOSITOR_IMAGE_TRANSPORT -DUSE_AURA=1 -DUSE_ASH=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_OZONE=1 -DUSE_DEFAULT_RENDER_THEME=1 -DUSE_LIBJPEG_TURBO=1 -DENABLE_ONE_CLICK_SIGNIN -DENABLE_PRE_SYNC_BACKUP -DENABLE_REMOTING=1 -DENABLE_WEBRTC=1 -DENABLE_MEDIA_ROUTER=1 -DUSE_PROPRIETARY_CODECS -DENABLE_PEPPER_CDMS -DENABLE_CONFIGURATION_POLICY -DENABLE_NOTIFICATIONS -DENABLE_HIDPI=1 -DENABLE_TOPCHROME_MD=1 -DUSE_UDEV -DDONT_EMBED_BUILD_METADATA -DENABLE_TASK_MANAGER=1 -DENABLE_EXTENSIONS=1 -DENABLE_PLUGINS=1 -DENABLE_SESSION_SERVICE=1 -DENABLE_THEMES=1 -DENABLE_AUTOFILL_DIALOG=1 -DENABLE_BACKGROUND=1 -DENABLE_GOOGLE_NOW=1 -DCLD_VERSION=2 -DENABLE_PRINTING=1 -DENABLE_BASIC_PRINTING=1 -DENABLE_PRINT_PREVIEW=1 -DENABLE_SPELLCHECK=1 -DENABLE_CAPTIVE_PORTAL_DETECTION=1 -DENABLE_APP_LIST=1 -DENABLE_SETTINGS_APP=1 -DENABLE_SUPERVISED_USERS=1 -DENABLE_MDNS=1 -DENABLE_SERVICE_DISCOVERY=1 -DV8_USE_EXTERNAL_STARTUP_DATA -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DSAFE_BROWSING_SERVICE -DBORINGSSL_IMPLEMENTATION -DBORINGSSL_NO_STATIC_INITIALIZER -DUSE_LIBPCI=1 -DUSE_NSS_CERTS=1 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -Igen -I../../third_party/boringssl/src/include -I../../third_party/boringssl/src/crypto -fstack-protector --param=ssp-buffer-size=4  -pthread -fno-strict-aliasing -Wno-unused-parameter -Wno-missing-field-initializers -fvisibility=hidden -pipe -fPIC -Wno-unused-local-typedefs -Wno-format -Wno-unused-result -m64 -march=x86-64 -O2 -fno-ident -fdata-sections -ffunction-sections -funwind-tables -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -D_FORTIFY_SOURCE=2  -c ../../third_party/boringssl/src/crypto/bio/socket_helper.c -o obj/third_party/boringssl/src/crypto/bio/boringssl.socket_helper.o
    ../../third_party/boringssl/src/crypto/bio/socket_helper.c: In function â€˜bio_ip_and_port_to_socket_and_addrâ€™:
    ../../third_party/boringssl/src/crypto/bio/socket_helper.c:42:19: error: storage size of â€˜hintâ€™ isnâ€™t known
       struct addrinfo hint, *result, *cur;
                       ^
    ../../third_party/boringssl/src/crypto/bio/socket_helper.c:51:9: warning: implicit declaration of function â€˜getaddrinfoâ€™ [-Wimplicit-function-declaration]
       ret = getaddrinfo(hostname, port_str, &hint, &result);
             ^
    ../../third_party/boringssl/src/crypto/bio/socket_helper.c:54:27: warning: implicit declaration of function â€˜gai_strerrorâ€™ [-Wimplicit-function-declaration]
         ERR_add_error_data(1, gai_strerror(ret));
                               ^
    ../../third_party/boringssl/src/crypto/bio/socket_helper.c:60:36: error: dereferencing pointer to incomplete type â€˜struct addrinfoâ€™
       for (cur = result; cur; cur = cur->ai_next) {
                                        ^
    ../../third_party/boringssl/src/crypto/bio/socket_helper.c:79:3: warning: implicit declaration of function â€˜freeaddrinfoâ€™ [-Wimplicit-function-declaration]
       freeaddrinfo(result);
       ^
    ninja: build stopped: subcommand failed.

Google suggested that _GNU_SOURCE/_POSIX_SOURCE needed to be defined for addrinfo stuff to work; however, _POSIX_SOURCE is already defined in that file. Adding _GNU_SOURCE appears to have 'fixed' the issue, though - but I might yet come across some other problem.

**Comment by rakuco** [comment]
With this combination of compiler and glibc, I think you will need the following boringssl patches:
* https://boringssl.googlesource.com/boringssl/+/241364c6f4d44165ce2dc707b9ad141dcc880d1b
* https://boringssl.googlesource.com/boringssl/+/7ca4b42146052d2cd108582daa2ddc64da74f959 (if you are building with NaCl)

FWIW, I just tried a build with `clang=0` here on an Ubuntu 14.04LTS installation and it worked fine with an older compiler and glibc.

**Comment by hobbitalastair** [comment]
Thanks! They look like they might do it... I'll test them out once I've finished the current build.

**Comment by hobbitalastair** [comment]
Built fine with those two patches, thanks @rakuco.

**Comment by kalyankondapally** [comment]
Should we close this ?

**Comment by rakuco** [comment]
The branch is also missing a `RELEASE-NOTES.txt`.

**Comment by kalyankondapally** [comment]
@rakuco  Will push that and close this. Sent you an email about this.

**Comment by kalyankondapally** [comment]
@joone  had some issues with NACL. Waiting on his response before this can be closed.
